# -*- coding: utf-8 -*-
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPalette, QBrush, QPixmap
from PyQt5.QtWidgets import QMainWindow, QApplication

from GUI.attribute import Attribute
from GUI.detect import Detect
from GUI.find import Find
from GUI.stream import Stream
from GUI.verify import Verify


# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnAttribute = QtWidgets.QPushButton(self.centralwidget)
        self.btnAttribute.setGeometry(QtCore.QRect(59, 230, 190, 60))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.btnAttribute.setFont(font)
        self.btnAttribute.setObjectName("btnAttribute")
        self.btnStream = QtWidgets.QPushButton(self.centralwidget)
        self.btnStream.setGeometry(QtCore.QRect(310, 230, 190, 60))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.btnStream.setFont(font)
        self.btnStream.setObjectName("btnStream")
        self.btnDetect = QtWidgets.QPushButton(self.centralwidget)
        self.btnDetect.setGeometry(QtCore.QRect(560, 230, 190, 60))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.btnDetect.setFont(font)
        self.btnDetect.setObjectName("btnDetect")
        self.btnFind = QtWidgets.QPushButton(self.centralwidget)
        self.btnFind.setGeometry(QtCore.QRect(60, 350, 190, 60))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.btnFind.setFont(font)
        self.btnFind.setObjectName("btnFind")
        self.btnVerify = QtWidgets.QPushButton(self.centralwidget)
        self.btnVerify.setGeometry(QtCore.QRect(310, 350, 190, 60))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.btnVerify.setFont(font)
        self.btnVerify.setObjectName("btnVerify")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 771, 161))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btnAttribute.clicked.connect(MainWindow.btnAttribute_Clicked) # type: ignore
        self.btnStream.clicked.connect(MainWindow.btnStream_Clicked) # type: ignore
        self.btnDetect.clicked.connect(MainWindow.btnDetect_Clicked) # type: ignore
        self.btnFind.clicked.connect(MainWindow.btnFind_Clicked) # type: ignore
        self.btnVerify.clicked.connect(MainWindow.btnVerify_Clicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        palette = QPalette()
        palette.setBrush(QPalette.Background, QBrush(QPixmap("./GUI/background.jpg")))
        self.setPalette(palette)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnAttribute.setText(_translate("MainWindow", "Face Attribute(image)"))
        self.btnStream.setText(_translate("MainWindow", "Face Attribute(Video)"))
        self.btnDetect.setText(_translate("MainWindow", "Face Detector"))
        self.btnFind.setText(_translate("MainWindow", "Facial Recognition"))
        self.btnVerify.setText(_translate("MainWindow", "Face Verification"))
        self.label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:36pt; font-weight:600; color:#3068ea;\">Deepface</span></p>\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p>\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:11pt; color:#3068ea;\">----Face Recognition and Facial Attribute Analysis</span></p></body></html>"))


class FirstWindowActions(Ui_MainWindow, QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def btnAttribute_Clicked(self):
        self.scend_window = Attribute_Action()
        self.scend_window.show()
        self.close()

    def btnStream_Clicked(self):
        self.scend_window = Stream_Action()
        self.scend_window.show()
        self.close()

    def btnDetect_Clicked(self):
        self.scend_window = Detect_Action()
        self.scend_window.show()
        self.close()

    def btnFind_Clicked(self):
        self.scend_window = Find_Action()
        self.scend_window.show()
        self.close()

    def btnVerify_Clicked(self):
        self.scend_window = Verify_Action()
        self.scend_window.show()
        self.close()

class Attribute_Action(Attribute, QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        # self.back.clicked.connect(self.go_back)

    def go_back(self):
        self.window = FirstWindowActions()
        self.window.show()
        self.close()

class Stream_Action(Stream, QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        # self.back.clicked.connect(self.go_back)

    def go_back(self):
        self.window = FirstWindowActions()
        self.window.show()
        self.close()

class Detect_Action(Detect, QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        # self.back.clicked.connect(self.go_back)

    def go_back(self):
        self.window = FirstWindowActions()
        self.window.show()
        self.close()

class Find_Action(Find, QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        # self.back.clicked.connect(self.go_back)

    def go_back(self):
        self.window = FirstWindowActions()
        self.window.show()
        self.close()

class Verify_Action(Verify, QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        # self.back.clicked.connect(self.go_back)

    def go_back(self):
        self.window = FirstWindowActions()
        self.window.show()
        self.close()

if __name__ == '__main__':
    app = QApplication(sys.argv)
    # 显示创建的界面
    MainWindow = FirstWindowActions()  # 创建窗体对象
    MainWindow.show()  # 显示窗体

    sys.exit(app.exec_())  # 程序关闭时退出进程
